### ISSUE TITLE
cargo run提示错误

### ISSUE THREAD

**Issue by tokkyy** [hazukieq/Yporaject#1]
在这一步执行cargo run这一步会出现error: could not find `Cargo.toml` in `XXX` or any parent directory 的错误会影响激活的失败吗？
![image](https://github.com/hazukieq/Yporaject/assets/121850916/e9a0fc25-b08c-4100-bc3c-b4d160ce2264)

**Comment by hazukieq** [comment]
> 在这一步执行cargo run这一步会出现error: could not find `Cargo.toml` in `XXX` or any parent directory 的错误会影响激活的失败吗？
> ![image](https://github.com/hazukieq/Yporaject/assets/121850916/e9a0fc25-b08c-4100-bc3c-b4d160ce2264)
> 

会影响的。

你可以尝试:
- `cp Cargo.toml /usr/shared/typora`，然后重新运行 cargo run
- 确保复制过来的是二进制程序 `node_inject`，然后给其赋予执行权限` sudo chmod +x node_inject` ，然后在 /usr/shared/typora目录下执行 `./node_inject`

希望可以帮助到您！

**Comment by 2000PJL** [comment]
你好，我复制了Cargo.toml到/usr/share/typora目录，重新运行cargo run时抛出了下面的错误：
error: failed to parse manifest at `/usr/share/typora/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
，我执行./node_inject时终端给出了以下提示：
You may have already installed the hook.Please check manually.
，请问这该如何解决呀？

**Comment by hazukieq** [comment]
> 你好，我复制了Cargo.toml到/usr/share/typora目录，重新运行cargo run时抛出了下面的错误：
> error: failed to parse manifest at `/usr/share/typora/Cargo.toml`
> 
> Caused by:
>   no targets specified in the manifest
>   either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
> ，我执行./node_inject时终端给出了以下提示：
> You may have already installed the hook.Please check manually.
> ，请问这该如何解决呀？

你好，不是必须复制 Cargo.toml到typora目录的。我上面给的是两种解决方案。你只需要择其一修正错误即可。

其实，cp node_inject到 /usr/shaed/typora后，赋予执行权限 `sudo chmod +x node_inject`,然后运行`./node_inject` 即可。

```bash
You may have already installed the hook.Please check manually.```说明你已经运行成功。不需要再重复运行。

请按接下来的步骤去获取激活码即可。祝好运！

**Comment by 2000PJL** [comment]
已经OK了，谢谢，出现：Failed to access the license server. Please check your network or try again later的原因是没有勾过中国大陆的激活服务器

**Comment by tokkyy** [comment]
我在执行./node_inject后的提示不是：
You may have already installed the hook.Please check manually.
而是：
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:25:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by hazukieq** [comment]
> 我在执行./node_inject后的提示不是：
> You may have already installed the hook.Please check manually.
> 而是：
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:25:63
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

若/usr/shared/typora/下存在Cargo.toml，则移除掉。然后使用第二种方法。

**Comment by tokkyy** [comment]
问题得到解决，谢谢。不过激活会因更新而失效吗？

**Comment by hazukieq** [comment]
> 问题得到解决，谢谢。不过激活会因更新而失效吗？

不会，会永久有效。具体原理请看第一条参考资料

**Comment by tokkyy** [comment]
这是目前最佳方法，感谢！

**Comment by hazukieq** [comment]
> > 问题得到解决，谢谢。不过激活会因更新而失效吗？
> 
> 会失效。更新后需要再运行，重新激活。具体原理请看第一条参考资料

更新软件后，app.asar可能会被覆盖掉，所以需要重新hook。资料那里，作者就激活原理解释的挺详细了的(笑)
