### ISSUE TITLE
mac-Typora-filepath

### ISSUE THREAD

**Issue by KagaShirou** [hazukieq/Yporaject#2]
Hi, I follow the step until to cp the inject node to the file of typora but I can get the right file path , because typora is an img, I use the path /Applications/Typora.app/Contents, it does not help. Can you give me some advices?

**Comment by hazukieq** [comment]
hi,friend!

The generated binary execution program is designed to inject some code into the app. asar to hijack the verification process. 
As long as an activation code that meets Typora's local judgment is entered at the input location, it can enter the network verification process and be returned with the correct verification data by the hook code.

 So, you can try unzipping the AppImage package and check if the app. sar file exists in the unzipped directory. If so, you can try the following:
1. Please copy the generated binary execution program into this directory and execute the binary program
2. Repackage into AppImage program

---
生成的二进制执行程序是为了给app.asar注入部分代码，以实现对验证流程的劫持，只要在输入激活码的地方输入能够满足typora本地判断的激活码即可。
进入网络验证流程并被hook代码返回正确的验证数据。

所以，你可以尝试解压AppImage包，检查解压目录下是否存在app.asar文件。
若有，你可以进行以下尝试:
1. 请复制生成的二进制执行程序到这个目录下，并执行该二进制程序
2.重新打包成AppImage程序

**Comment by hazukieq** [comment]
> Hi, I follow the step until to cp the inject node to the file of typora but I can get the right file path , because typora is an img, I use the path /Applications/Typora.app/Contents, it does not help. Can you give me some advices?

I do not test this on mac platform. if  the file `app.asar` has found  in the installed path of typora, this way would work correctly. 

So you can make a try:
1. check if app.asar exists in the typora directory.
2. if so, just copy the executable binary into that directory and execute it. 

```bash
./node_inject
// You will see some outputs on  screen
```
3. remove the binary,  go back to this project and use another binary to generate the codes for activation
4. open typora software, and input the codes to activate.

no matter your software format is .exe or .deb,.AppImage, just make sure `app.asar` exists in some directory, and this way will be work theoretically.

test passed platform:
[x] linux ubuntu 
[x] windows

**Comment by hazukieq** [comment]
Typora can not activated by  this way on mac os.
