### ISSUE TITLE
是否失效了？

### ISSUE THREAD

**Issue by xklong** [hazukieq/Yporaject#3]
使用typora1.6.6
kylin系统
生成的激发码填入后，提示请输入正确的序列号
重新运行后还是如此

**Comment by hazukieq** [comment]
你确定按文档步骤生成node_inject，移动到Typora安装目录，并运行了吗？
如果这样子依旧不成功的话，我也不清楚了。
你可以看看下方的参考资料。

**Comment by xklong** [comment]
> 你确定按文档步骤生成node_inject，移动到Typora安装目录，并运行了吗？ 如果这样子依旧不成功的话，我也不清楚了。 你可以看看下方的参考资料。

是的，我手动检查看到node_inject已经移动到Typora安装目录，并运行的。
我卸载重新装一遍试试

**Comment by xklong** [comment]
还是没有成功，能否帮忙看下，这是在安装目录运行的时候出的信息


kylin@kylin-pc:/usr/share/typora$ ./node_inject
extracting node_modules.asar
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:25:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by xklong** [comment]
> 还是没有成功，能否帮忙看下，这是在安装目录运行的时候出的信息
> 
> kylin@kylin-pc:/usr/share/typora$ ./node_inject extracting node_modules.asar thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:25:63 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

搞定了，已激活成功，谢谢大佬

**Comment by hazukieq** [comment]
> 还是没有成功，能否帮忙看下，这是在安装目录运行的时候出的信息
> 
> 
> kylin@kylin-pc:/usr/share/typora$ ./node_inject
> extracting node_modules.asar
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:25:63
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 

原来是没有读写权限导致的呀，难怪你之前激活不了。因为这个程序并没有成功运行。

**Comment by hazukieq** [comment]
> > 还是没有成功，能否帮忙看下，这是在安装目录运行的时候出的信息
> > 
> > kylin@kylin-pc:/usr/share/typora$ ./node_inject extracting node_modules.asar thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:25:63 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 搞定了，已激活成功，谢谢大佬

嘿嘿嘿还得多亏你自己的动手排查能力(笑)

**Comment by xklong** [comment]
> > > 还是没有成功，能否帮忙看下，这是在安装目录运行的时候出的信息
> > > kylin@kylin-pc:/usr/share/typora$ ./node_inject extracting node_modules.asar thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:25:63 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > 
> > 
> > 搞定了，已激活成功，谢谢大佬
> 
> 嘿嘿嘿还得多亏你自己的动手排查能力(笑)

还是多谢大佬提供这么详细的教程

> > 还是没有成功，能否帮忙看下，这是在安装目录运行的时候出的信息
> > kylin@kylin-pc:/usr/share/typora$ ./node_inject
> > extracting node_modules.asar
> > thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:25:63
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 原来是没有读写权限导致的呀，难怪你之前激活不了。因为这个程序并没有成功运行。
在./node_inject前面加一个sudo就可以了。还是多谢大佬提供这么详细的教程，真的太感谢了
