### ISSUE TITLE
更新后无法激活

### ISSUE THREAD

**Issue by lkamh** [hazukieq/Yporaject#7]
大佬你好，我之前已经激活一次，这次想更新一下，然后卸载后，重装了1.7.6的版本，结果按照流程下来，无法激活，过程中遇到这么一行代码，不知道怎么解决，请大佬指教一二。

`You may have already installed the hook.Please check manually.`

**Comment by hazukieq** [comment]
您好，我想可能导致的原因是: 之前的/usr/share/typora 文件夹没清理干净。因为里面有一个node文件夹，hook函数会判断这个文件夹是否存在来判断你是否在之前激活过。

![Uploading {148407-x-5453111032944}(1).png …]()
![{148407-x-5345117435496}(1).png](https://github.com/hazukieq/Yporaject/assets/77765021/d6309658-7d24-484f-90c4-70aabe07cd00)


所以，你可以通过删除 node文件夹来重新激活。或者移除 /usr/share/typora整个文件夹，重新安装typora再重新激活。

**Comment by lkamh** [comment]
> 您好，我想可能导致的原因是: 之前的/usr/share/typora 文件夹没清理干净。因为里面有一个node文件夹，hook函数会判断这个文件夹是否存在来判断你是否在之前激活过。
> 
> ![{148407-x-5453111032944}(1).png](https://private-user-images.githubusercontent.com/77765021/294880299-d40c0538-0dc4-42b6-bf79-3538c3a64387.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjI5MTAsIm5iZiI6MTcwNDc2MjYxMCwicGF0aCI6Ii83Nzc2NTAyMS8yOTQ4ODAyOTktZDQwYzA1MzgtMGRjNC00MmI2LWJmNzktMzUzOGMzYTY0Mzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAxMTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNzlkYjRhZGZjMWI0YjZkNzNmMjY4ZmY5ZjQ4YmY0YzA0NGQwZDJjYWFlZjJlOTA1YmYwNDllMGE1OWJlNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0f6s1xX84iyq8uJq4UVUqrhnzHWH-o6H106aCRNxseQ)
> 
> ![{148407-x-5345117435496}(1).png](https://private-user-images.githubusercontent.com/77765021/294879849-d6309658-7d24-484f-90c4-70aabe07cd00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjI5MTAsIm5iZiI6MTcwNDc2MjYxMCwicGF0aCI6Ii83Nzc2NTAyMS8yOTQ4Nzk4NDktZDYzMDk2NTgtN2QyNC00ODRmLTkwYzQtNzBhYWJlMDdjZDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAxMTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMWFlN2RmMzgyMzIzNmE0OWUxMDc5NDJhNWZmNmMzZTZiMjhiMjllY2RjOGExZDVmNWYyMGVkMWZkOTE2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FmOn5bqn_dv9xpM96GMyDLvG3P6fIojnnCVvimC8-GA)
> 
> 所以，你可以通过删除 node文件夹来重新激活。或者移除 /usr/share/typora整个文件夹，重新安装typora再激活。

感谢大佬，确实是这样的，typora文件里面有node文件夹，我卸载后，将typora文件夹删除以后，就可以了。再次感谢大佬指导
