### ISSUE TITLE
Typora版本问题十分关键

### ISSUE THREAD

**Issue by 2653888596** [hazukieq/Yporaject#8]
非常感谢作者大佬的激活教程，但是我是从知乎上看到您的文章，一开始在知乎上下载了Typora 1.6.6版本，导致作者的序列号失效，在此提醒大家，一定要按照此github中的版本 **Typora 1.7.4 版本**进行安装！
再次感谢

**Comment by MathhubDouglas** [comment]
> 非常感谢作者大佬的激活教程，但是我是从知乎上看到您的文章，一开始在知乎上下载了Typora 1.6.6版本，导致作者的序列号失效，在此提醒大家，一定要按照此github中的版本 **Typora 1.7.4 版本**进行安装！ 再次感谢

![image](https://github.com/hazukieq/Yporaject/assets/132361107/60e28245-07d9-4b80-b8f9-c365f5edb2d8)
![image](https://github.com/hazukieq/Yporaject/assets/132361107/ec83f2bb-6913-48ea-ae39-a980f53eeedb)

好像也没必要必须1.7.4，最新版本1.8.10测试激活成功,系统环境: debian12.5 cargo 1.77.2

**Comment by Howardzhangdqs** [comment]
官网上好像1.7.4版本的安装包被下架了，应该安装哪个版本的
![image](https://github.com/user-attachments/assets/a72fe415-95dd-44de-aa4a-a119091ab041)

**Comment by hazukieq** [comment]
就安装最新版即可。激活时记得勾选 国内服务器，不然会卡住。











李涛

---原始邮件---
发件人: "Howard ***@***.***&gt;
发送时间: 2024年10月21日(周一) 上午7:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [hazukieq/Yporaject] ---Warning---Typora版本问题十分关键 (Issue #8)




 
官网上好像1.7.4版本的安装包被下架了，应该安装哪个版本的
 image.png (view on web)

**Comment by hazukieq** [comment]
> 官网上好像1.7.4版本的安装包被下架了，应该安装哪个版本的
> ![image](https://github.com/user-attachments/assets/a72fe415-95dd-44de-aa4a-a119091ab041)
> 

最新版即可，记得勾选国内服务器，不然激活不成功。

**Comment by Howardzhangdqs** [comment]
感谢大佬，已成功
