### ISSUE TITLE
Arch Linux 上 Typora1.7.6-2 文件目录无法找到

### ISSUE THREAD

**Issue by 2261700275** [hazukieq/Yporaject#9]
我应该是成功运行了程序，但是激活时仍存在问题，提示请输入正确的激活码
  >❯ ./node_inject
  extracting node_modules.asar
  adding hook.js
  applying patch
  packing node_modules.asar
  done!
  ❯ ls
   chrome_100_percent.pak      libEGL.so              LICENSES.chromium.html   snapshot_blob.bin
   chrome_200_percent.pak      libffmpeg.so           locales                  Typora
   chrome_crashpad_handler     libGLESv2.so           node                     v8_context_snapshot.bin
   chrome-sandbox              libvk_swiftshader.so   node_inject              version
  'DO NOT ADD FILES HERE.md'   libvulkan.so.1         resources                vk_swiftshader_icd.json
   icudtl.dat                  LICENSE                resources.pak
  ❯ cd $cur
  ❯ cd license-gen
  ❯ cargo build
     Compiling fastrand v1.8.0
     Compiling random-string v1.0.0
     Compiling license-gen v0.1.0 (/home/yun/Templates/activate typora/Yporaject/license-gen)
      Finished dev [unoptimized + debuginfo] target(s) in 0.29s
  ❯ cargo run
      Finished dev [unoptimized + debuginfo] target(s) in 0.00s
       Running `target/debug/license-gen`
  License for you: VSXKFY-5R5A5B-VJ2WAR-DYSAFZ

我的项目存在不一样的地方是我的软件安装目录不是/usr/share/typora, 而是~/.cache/yay/typora-electron/src/usr/share/typora/
文件夹内的内容应该是一样的

为什么不安装原版？
我尝试安装原版后，激活界面无法点开，持续卡在此界面
![Screenshot_20240126_115938](https://github.com/hazukieq/Yporaject/assets/115214316/c9f6582b-c4b7-461d-abf5-6ebc6d7acb01)

**Comment by hazukieq** [comment]
> 我应该是成功运行了程序，但是激活时仍存在问题，提示请输入正确的激活码
>   >❯ ./node_inject
>   extracting node_modules.asar
>   adding hook.js
>   applying patch
>   packing node_modules.asar
>   done!
>   ❯ ls
>    chrome_100_percent.pak      libEGL.so              LICENSES.chromium.html   snapshot_blob.bin
>    chrome_200_percent.pak      libffmpeg.so           locales                  Typora
>    chrome_crashpad_handler     libGLESv2.so           node                     v8_context_snapshot.bin
>    chrome-sandbox              libvk_swiftshader.so   node_inject              version
>   'DO NOT ADD FILES HERE.md'   libvulkan.so.1         resources                vk_swiftshader_icd.json
>    icudtl.dat                  LICENSE                resources.pak
>   ❯ cd $cur
>   ❯ cd license-gen
>   ❯ cargo build
>      Compiling fastrand v1.8.0
>      Compiling random-string v1.0.0
>      Compiling license-gen v0.1.0 (/home/yun/Templates/activate typora/Yporaject/license-gen)
>       Finished dev [unoptimized + debuginfo] target(s) in 0.29s
>   ❯ cargo run
>       Finished dev [unoptimized + debuginfo] target(s) in 0.00s
>        Running `target/debug/license-gen`
>   License for you: VSXKFY-5R5A5B-VJ2WAR-DYSAFZ
> 
> 我的项目存在不一样的地方是我的软件安装目录不是/usr/share/typora, 而是~/.cache/yay/typora-electron/src/usr/share/typora/
> 文件夹内的内容应该是一样的
> 
> 为什么不安装原版？
> 我尝试安装原版后，激活界面无法点开，持续卡在此界面
> ![Screenshot_20240126_115938](https://github.com/hazukieq/Yporaject/assets/115214316/c9f6582b-c4b7-461d-abf5-6ebc6d7acb01)
> 

您好！
通过 Arch 源安装的话，需要找到 typora 文件存储的地方(即 typora 程序启动时用到的文件都储存在此目录)，然后将 `node_inject` 挪动过去再执行。——你可以通过 `whereis typora` 查找。

通过你的描述，似乎家目录下的 `.cache` 是 typora 文件储存的地方，不知道你有没有尝试过将 `node_inject` 移动到此执行后激活呢？注意: `node_inject` 执行后，若 typora 应用打开的话需重启。
